### ISSUE TITLE
As an external data analyst, I would like to have all Bluetooth raw data anonymized so to avoid any privacy concern

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/BluetoothTrafficElaboration#1]
Suggestion to use a certain hashing function

**Comment by bertolla** [comment]
I thought about it, and I think that the best way to guarantee security, would be to encrypt the MAC-addresses already on the bluetooth-box. 
@rcavaliere  Is it be possible to access the boxes?

**Comment by ohnewein** [comment]
@bertolla what do you mean with encrypting the MAC-addresses? These addresses are already hash-codes. There is no direct connection to a person. So encrypting them once more would not increase anonymity.

**Comment by bertolla** [comment]
If we public this data and somebody gets this data he could theoretically scan bluetooths and correlate the one he finds with the existing data. Theoretically he can deduce when you passed at what time at which point. To avoid this anonymizing it would deny this possibility.
This is how I understood  the task.
Maybe Roberto can clarify.

**Comment by bertolla** [comment]
I finished the anonymization of data on the testserver and implemented it also on the java datacollector.
I think it could be risky to do it on the raspberries since they are probably not encrypted and the secret key could be stolen easily. 
@rcavaliere 
To test it:
- check on new testserver on measurementstring and  measurementstringhistory (I will send you credentials)
- check if the anonymization worked through datacollector (measurementstring-> station_id 498)

**Comment by rcavaliere** [comment]
@bertolla, thanks for the feedback, I will test this. 
For the answer to @ohnewein, 100% right - that's the reason for this user story.

**Comment by rcavaliere** [comment]
@bertolla checked this, seems OK.

**Comment by rcavaliere** [comment]
@Piiit @bertolla please put this new feature in production

**Comment by Piiit** [comment]
@rcavaliere @bertolla I had some issues the last two days with our release pipelines and so I were not able to put this on production. Now, as I released a new core test-version, I want to re-test this DC to be sure that everything works. I test it myself and put it in production when I am ready. Hopefully, this week or at the beginning of the next. 

@rcavaliere How urgent is it?

**Comment by rcavaliere** [comment]
@Piiit it's not so urgent, it's ok to go to next week.

**Comment by Piiit** [comment]
@rcavaliere Done, it is on production :-)

It was easier as I thought!
